remote_theme: "owasp/www--site-theme"
plugins:
 - jekyll-include-cache-0.2.0
 - jemoji
 - jekyll-redirect-from
include:
 - 'stammtische'
 - 'stammtische/hamburg'
 - 'stammtische/frankfurt'
 - 'chapter_meetings'
